### ISSUE TITLE
Limit stdout to user specified byte count

### ISSUE THREAD

**Issue by nickjones** [nickjones/proc_box#3]
Some use cases would rather end the job when exceeding a certain level of stdout (redirected to a log file) over blowing up a shared disk with other jobs.  Thoughts on requirements:
- Flags for enable/disable (disabled by default)
- Threshold value hopefully with units (e.g. 100GB)
- Perhaps a proc_status AMQP routing key (separate from statistics) that offers a regular heartbeat and if the limit has been exceeded?

**Comment by nickjones** [comment]
@Elleryia can you look at this branch and see if it meets the overall needs?  I didn't implement STDERR limiting but that seems less likely as a large log producer.

**Comment by yerfdogyrag** [comment]
Just as a note: can you please make sure that if there is no limit that it doesn't touch stdout at all?  I have some jobs that run interactive with command-line editing, which is incompatible with your current code.

Thanks,
Gary

**Comment by nickjones** [comment]
I think that's a reasonable requirement. The redirect logic should probably operate on bytes too.  I'm assuming the scanner is looking for line endings.

**Comment by nickjones** [comment]
@Elleryia take a look at issues/3b if you can.  I still can't get stdin piping to work.  I also changed the threshold stuff a bit to panic in the event it can't kill the child process after 100 attempts.

**Comment by matt-wright-gh** [comment]
@nickjones Yeah Ill take a look.
