### ISSUE TITLE
exchange must be durable or else messages dont get through. 

### ISSUE THREAD

**Issue by matt-wright-gh** [nickjones/proc_box#5]

**Comment by matt-wright-gh** [comment]
The command messages mark the queue as durable while the stats dont, since the command comes first the stats messages are not picked up.

**Comment by nickjones** [comment]
I can't remember what we ended up with after debugging this.  I seem to recall if we didn't match the defined (existing) exchange, we had problems.  However, I don't remember what we changed to make this work.

**Comment by nickjones** [comment]
I'm not sure this is a problem in proc_box but not an error in manually making the exchange.  This works fine for me with the default amq.topic exchange.

**Comment by matt-wright-gh** [comment]
I would agree. I concur with closing this.
